Repository bucketplace/ci, pull requests merged in 2022-12, with the labels that each got.

#6 [COREPL-326] golang reusable ci
  .github/workflows/check-golang.yml
Labels: size/XL

#7 SC-11: "Run Node.js Test" reusable 액션에 base dir 및 node.js 버전 지정 옵션 추가
  .github/workflows/check-nodejs.yml
Labels: enhancement, size/S

#8 feat: check-kotlin-gradle에 sonar-token input 추가
  .github/workflows/check-kotlin-gradle.yml
Labels: size/S

#9 chore: add sonarqube exclusions option
  .github/workflows/check-golang.yml
Labels: size/XS, team/corepl
