Repository bucketplace/ci, pull requests merged in 2023-01, with the labels that each got.

#10 [COREPL-254] feat: Mortar Build Cache 적용
  .github/actions/load-build-cache/action.yml
  .github/actions/store-build-cache/action.yml
  .github/workflows/check-kotlin-gradle.yml
Labels: size/L, team/corepl

#11 [COREPL-183] go package deploy ci
  .github/workflows/check-golang.yml
  .github/workflows/deploy-go-package.yml
Labels: team/corepl, size/M

#12 chore: update pack version
  .github/workflows/deploy-go-package.yml
Labels: size/XS, team/corepl

#14 fix: PR이 아닐 때 "Add Result To Summary"step을 실행하지 않는다
  .github/workflows/check-golang.yml
Labels: size/XS, team/corepl
