Repository bucketplace/ci, pull requests merged in 2023-03, with the labels that each got.

#18 feat: jacoco-reports 파라미터 추가
  .github/workflows/check-kotlin-gradle.yml
Labels: size/XS, team/corepl

#19 chore: replace deprecated `set-output` command with environment file
  .github/actions/release-tag-finder/action.yml
Labels: size/XS, team/corepl

#20 SC-79: FE release workflow - snapshot 액션에서 릴리즈된 패키지/버전 정보 알 수 있도록 출력
  .github/workflows/reusable-changesets-snapshot.yml
Labels: enhancement, size/S, team/corepl

#21 SC-50: FE release workflow - comments로 트리거하는 snapshot 워크플로우 추가
  .github/workflows/reusable-changesets-snapshot-with-comments.yml
Labels: enhancement, team/corepl, size/M

#22 SC-97: CI 저장소 `main` 브랜치에 피쳐가 병합되면 자동으로 배포하는 스크립트 추가
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  README.md
Labels: enhancement, size/L, team/corepl

#23 [COREPL-599] Go & Ginkgo version auto detect
  .github/workflows/check-golang.yml
Labels: size/S, team/corepl
