Repository bucketplace/ci, pull requests merged in 2023-08, with the labels that each got.

#34 SC-299: 워크플로우 Node.js 버전 업그레이드
  .github/workflows/check-nodejs.yml
  .github/workflows/reusable-changesets-prerelease.yml
  .github/workflows/reusable-changesets-publish.yml
  .github/workflows/reusable-changesets-snapshot-with-comments.yml
  .github/workflows/reusable-changesets-snapshot.yml
Labels: enhancement, size/S, team/corepl

#38 COREPL-1211 feat: support mortar multi-version
  .github/workflows/check-kotlin-gradle.yml
Labels: size/XS, team/corepl

#39 SC-350: SonarCloud: FE 워크플로우에서 lint/lcov 명령이 non-zero exit 인 경우에도 재개 허용
  .github/workflows/reusable-sonarcloud-analysis-nodejs.yml
Labels: enhancement, size/XS, team/corepl

#40 [SC-350] SonarCloud: FE 워크플로우에 SONAR_TOKEN 필수 시크릿으로 추가
  .github/workflows/reusable-sonarcloud-analysis-nodejs.yml
Labels: bug, size/XS, team/corepl
