Repository bucketplace/ci, pull requests merged in 2023-06, with the labels that each got.

#25 COREPL-619 feat: add workflow for pack increment feature
  .github/workflows/deploy-go-package.yml
Labels: size/S, team/corepl

#27 COREPL-950 fix: set-output in jacoco-report action
  .github/workflows/check-kotlin-gradle.yml
Labels: size/XS, team/corepl

#28 chore: make ginkgo and sonarqube optional
  .github/workflows/check-golang.yml
Labels: team/corepl, size/M

#26 COREPL-963 feat: add version metadata in github_output
  .github/workflows/deploy-go-package.yml
Labels: size/S, team/corepl

#30 fix: double and operations
  .github/workflows/check-golang.yml
Labels: size/XS, team/corepl

#29 fix: deploy output
  .github/workflows/deploy-go-package.yml
Labels: size/S, team/corepl

#31 [COREPL-1035] feature: 멀티 모듈 배포 Action
  .github/actions/multimodule-changelog/README.md
  .github/actions/multimodule-changelog/action.yml
  .github/actions/multimodule-releaser/README.md
  .github/actions/multimodule-releaser/action.yml
  .github/actions/multimodule-releaser/images/await_review.png
  .github/actions/multimodule-releaser/images/env_enter.png
  .github/actions/multimodule-releaser/images/env_menu.png
  .github/actions/multimodule-releaser/images/env_rule.png
  .github/actions/multimodule-releaser/images/review_modal.png
  .github/actions/multimodule-releaser/images/run_workflow_modal.png
  .github/actions/multimodule-releaser/images/run_workflows.png
  .github/actions/multimodule-releaser/images/workflow_run_history.png
  .github/actions/release-and-dispatch/README.md
  .github/actions/release-and-dispatch/action.yml
Labels: size/L, team/corepl
