Repository bucketplace/ci, pull requests merged in 2024-01, with the labels that each got.

#54 [COMWEB-0] config: 빌드 스크립트 호출 시 env production 설정
  .github/workflows/reusable-changesets-publish.yml
Labels: size/XS, team/corepl

#55 [COREPL-1573] Fix: Update Setup Mortar Version (ignore-stats)
  .github/actions/setup-mortar/dist/index.js
  .github/actions/setup-mortar/index.js
Labels: team/corepl, size/XXL

#53 [COREPL-1565] `Web Checks` 워크플로우에서 memory limit이 cgroup-aware하도록 수정
  .github/workflows/check-web.yml
Labels: bug, size/XS, team/corepl

#52 [COREPL-1550] Remove unused permission + Add Custom Rules
  .github/workflows/.protolint.yaml
  .github/workflows/check-protolint.yaml
  .github/workflows/check-protolint.yml
Labels: team/corepl, size/M

#56 [SEARCH-2377] multimodule-changelog bump bug fix
  .github/actions/multimodule-changelog/action.yml
Labels: size/XS, team/corepl

#49 [SEARCH-2072] mortar preview, non-mortar preview action
  .github/workflows/mortar-preview-action.yaml
  .github/workflows/non-mortar-preview-action.yaml
Labels: size/L, team/corepl

#47 [SEARCH-2072] add mortar, non-mortar deploy action
  .github/workflows/mortar-build-and-push-action.yaml
  .github/workflows/mortar-deploy-action.yaml
  .github/workflows/mortar-preview-action.yaml
  .github/workflows/non-mortar-build-and-push-action.yaml
  .github/workflows/non-mortar-deploy-action.yaml
  .github/workflows/non-mortar-preview-action.yaml
Labels: size/XL, team/corepl

#57 [SEARCH-2424] release 태그 추출시 이상한 태그 들어오는 버그 수정
  .github/actions/latest-tag-finder/action.yml
Labels: size/XS, team/corepl
